name: Publish Extension (Prod)

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: |
          "Specify release version eg. 0.0.1"
        required: true
        default: ""
        type: string

defaults:
  run:
    shell: bash

jobs:
  publish-extension-dev:
    runs-on: ubuntu-latest
    env:
      Version: ${{ github.event.inputs.release-version }}
      ExtensionId: ${{ vars.EXT_ID }}
      AzExtPublishPat: ${{ secrets.AZ_EXT_PUBLISH_PAT_PROD }}
      Publisher: ${{ vars.AZ_PUBLISHER_PROD }}
      AppGuid: "c62b2217-14ac-41cc-883b-d47232837a03"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run publish-extension.sh script
        id: publish-extension
        run: |
          chmod +x scripts/*.sh
          ./scripts/publish-extension.sh $Version $ExtensionId $AzExtPublishPat $Publisher $AppGuid
